<?php

namespace CommandesBundle\Repository;

/**
 * ProduitPanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitPanierRepository extends \Doctrine\ORM\EntityRepository
{
}
