demande_offre_homepage:
    path:     /GestionDO
    defaults: { _controller: DemandeOffreBundle:Default:index }
Produits_antisalissure:
    path:     /P_a
    defaults: { _controller: DemandeOffreBundle:Default:index }

Offre:
    path:     /GestionDO/Offre
    defaults: { _controller: DemandeOffreBundle:Default:index }

Demande:
    path:     GestionDo/Demande
    defaults: { _controller: DemandeOffreBundle:Default:index }

Batiment:
    path:     /Batiment
    defaults: { _controller: DemandeOffreBundle:Default:index }

Industries:
    path:     /Indus
    defaults: { _controller: DemandeOffreBundle:Default:index }

Demenagemnt:
    path:     /Dememangement
    defaults: { _controller: DemandeOffreBundle:Default:index }

SmartHome:
    path:     /SH
    defaults: { _controller: DemandeOffreBundle:Default:index }

Coursier:
    path:     /Cr
    defaults: { _controller: DemandeOffreBundle:Default:index }
