demande_offre_homepage:
    path:     /GestionDO
    defaults: { _controller: DemandeOffreBundle:Default:index }
Produits_antisalissure:
    path:     /P_a
    defaults: { _controller: DemandeOffreBundle:Default:index }

Offre:
    path:     /GestionDO/Offre
    defaults: { _controller: DemandeOffreBundle:Default:index }

Demande:
    path:     /GestionDO/Demande
    defaults: { _controller: DemandeOffreBundle:Default:index }


affichage_la_liste_d_offre:
    path:     /prestataire/home/affichage
    defaults: { _controller: DemandeOffreBundle:Default:affichage }

affichage_la_liste_d_demande:
    path:     /client/home/affichageDemande
    defaults: { _controller: DemandeOffreBundle:Default:affichageDemande }

ajout_offre:
    path:     /prestataire/home/ajout
    defaults: { _controller: DemandeOffreBundle:Default:ajout }

modifier_une_offre:
    path:     /prestataire/home/modifier/{id}
    defaults: { _controller: DemandeOffreBundle:Default:modifier }

supprimer_une_offre:
    path:     /prestataire/home/supprimer/{id}
    defaults: { _controller: DemandeOffreBundle:Default:supprimer }

Afficher_All_offre:
    path:   /client/home/offre
    defaults: { _controller: DemandeOffreBundle:Default:afficherAllOffre }

Ajouter_demande:
    path: /client/home/demande/{id}
    defaults: { _controller: DemandeOffreBundle:Default:ajouterDemande }












Batiment:
    path:     /Batiment
    defaults: { _controller: DemandeOffreBundle:Default:index }

Industries:
    path:     /Indus
    defaults: { _controller: DemandeOffreBundle:Default:index }

Demenagemnt:
    path:     /Dememangement
    defaults: { _controller: DemandeOffreBundle:Default:index }

SmartHome:
    path:     /SH
    defaults: { _controller: DemandeOffreBundle:Default:index }

Coursier:
    path:     /Cr
    defaults: { _controller: DemandeOffreBundle:Default:index }
