services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  app.form.registration:
    class: UserBundle\Form\RegistrationType
    tags:
      - { name: form.type, alias: app_user_registration }
